### ISSUE TITLE
Einheiten movement

### ISSUE THREAD

**Issue by Richardk2n** [husten1997/KM#6]
Gruppe a selectiern weit weit weg schicken
Gruppe b selectiern
a hört auf sich zu bewegen

**Comment by husten1997** [comment]
Des machst easy Machst nen Handler für der solange läuft bis sich die Truppen an ort und Stelle befinden

**Comment by Richardk2n** [comment]
habs bereits repariert (eine zeile gelöscht) de eig. deprecated wa
